version: "3"
services:
  frontend:
    depends_on:
    - "backend"
    image: "${REGISTRY}/kompose-example/frontend:latest"
    build:
      context: "."
      dockerfile: "docker/frontend/Dockerfile"
    environment:
      BASE_API_URL: "http://backend:8080"
    ports:
    - "80:80"
  backend:
    image: "${REGISTRY}/kompose-example/backend:latest"
    build:
      context: "."
      dockerfile: "docker/backend/Dockerfile"
    ports:
    - "8080:8080"
